-- load all plugins config
require('plugins.lualine')
require('plugins.indent_blankline')
require('plugins.gitsigns')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.mason')
require('plugins.fidget')
require('plugins.nvim_cmp')
require('plugins.penvim')
require('plugins.nvim_tree')
require('plugins.cheatsheet')
require('plugins.aerial')
require('plugins.mini')
require('plugins.illuminate')

